ribbon:
  eager-load:
    enabled: true #开启饥饿加载提升第一次访问速度
    clients:
      - search-service #指定开启服务
feign:
  httpclient:
    enabled: true  # 开启httpClient开关,启动连接池,提升feign连接效率!
    max-connections: 200  #最大连接数量
    max-connections-per-route: 50  #单路径最大连接数
spring:
  profiles:
    active: mq  #激活mq的配置