spring:
  # 连接池配置
  datasource:
    url: jdbc:mysql://localhost:3306/store_admin?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: cache,mq,dev
  thymeleaf:
    cache: true  #开启缓存
    check-template: true  #检查模板是否存在
    check-template-location: true # 检查模板位置正确性 默认查找 resources templates文件夹内
    servlet:
      content-type: text/html # 直接嵌入到html文件中
    enabled: true
    encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-aliases-package: com.yecheng.pojo #设置别名a
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eager-load:
    enabled: true #开启饥饿加载提升第一次访问速度
    clients:
      - store-service #指定开启服务
feign:
  httpclient:
    enabled: true  # 开启httpClient开关,启动连接池,提升feign连接效率!
    max-connections: 200  #最大连接数量
    max-connections-per-route: 50  #单路径最大连接数
  client: #默认 1秒
    default: # 设置连接超时时间
      ConnectTimeOut: 10000
      ReadTimeOut: 10000 #设置读取数据超时时间

server:
  servlet:
    context-path: /admin

#OSS配置
#aliyun:
#  oss:
#    file:
#      # 控制台 - oss - 点击对应桶 - 概览 - 地域节点
#      endpoint: oss-cn-beijing.aliyuncs.com
#      keyid: LTAI5t82cN3TfofxJywKvoj5
#      keysecret: 7cPhJQBMNewuqXXnUiEjpj1l8YeONo
#      bucketname: store-b2c

#OSS配置
